{
  pkgs,
  zen-browser,
  helium,
  ...
}:
{
  environment.systemPackages = with pkgs; [
    ghostty
    zen-browser.packages.${pkgs.system}.beta
    helium.packages.${pkgs.system}.default
    chromium
    qutebrowser
    vesktop
    kdePackages.dolphin
    kdePackages.kio
    kdePackages.kio-extras
    nautilus
    kdePackages.ark
    unar
    unzip
    p7zip
    rar
    kdePackages.kolourpaint
    kdePackages.kdenetwork-filesharing
    kdePackages.discover
    gnome-calendar
    gnome-weather
    epiphany
    gnome-keyring
    seahorse
    trilium-desktop
    rnote
    qalculate-qt
    alarm-clock-applet
    mission-center
  ];
}
